# Generated by Django 2.1.7 on 2019-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('etiqueta', models.SlugField(verbose_name='Etiqueta')),
                ('descricao', models.CharField(max_length=60, verbose_name='Descricao')),
            ],
        ),
    ]
