# Generated by Django 2.1.7 on 2019-04-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedisciplinas', models.CharField(max_length=50, verbose_name='Nomedisciplinas')),
                ('sigladisciplinas', models.CharField(max_length=5, verbose_name='Sigladisciplinas')),
                ('etiquetadisciplinas', models.SlugField(verbose_name='Etiquetadisciplinas')),
                ('descricaodisciplinas', models.CharField(max_length=60, verbose_name='Descricaodisciplinas')),
            ],
        ),
    ]
