# Generated by Django 2.1.7 on 2019-04-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeprofessores', models.CharField(max_length=50, verbose_name='Nome')),
                ('siglaprofessores', models.CharField(max_length=5, verbose_name='Sigla')),
                ('etiquetaprofessores', models.SlugField(verbose_name='Etiqueta')),
            ],
        ),
    ]
